version: '3.8'
services:
  template:
    image: mysql:latest
    
    # 애플 실리콘 맥을 사용하는 경우 아래 platform 을 주석처리 해제
    # platform: linux/amd64
    volumes:
      - template:/data
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: template
    command:
      [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower_case_table_names=1' ]

volumes:
  template:
